services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./app:/var/www
    ports:
        - "8000:8000"
        - "5173:5173"
    depends_on:
      - db
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
